### ISSUE TITLE
2-Unit test

### ISSUE THREAD

**Issue by bence-t0th** [BME-MIT-IET/iet-hf2021-nekem-mind1#2]
Közösen egyeztettünk az elvégzendő feladatok beosztásáról.

**Comment by bence-t0th** [comment]
Main-en lévő projektben van minden eddigi munka, viszont a unit tesztek nem futnak le nálam. Lehet, hogy nálam van a probléma, de átnéznéd kérlek a main-en lévő projektet?

**Comment by smedu1999** [comment]
Átnéztem őket, nálam lefut minden, tehát a mainben jól van fent.

**Comment by bence-t0th** [comment]
![186510354_512312186474144_7006363512940111073_n](https://user-images.githubusercontent.com/48957481/118409386-7505f980-b68a-11eb-9a8d-57c7b98546fb.png)
